[package]
name = "random-facts"
version = "0.1.0"
authors = ["Thomas Mauran <78204354+thomas-mauran@users.noreply.github.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.20.1" }
